language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get -y update
  - sudo apt-get -y upgrade
  #Build tools
  - sudo apt-get -y install build-essential
  #OpenCV
  - sudo apt-get -y install libopencv-dev
  #BOOST
  - sudo apt-get -y install libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make all
  - ./optic-disc-detector-test